"""add size field to Project table

Revision ID: 646063b9a8a7
Revises: fe566d6c618a
Create Date: 2023-04-26 17:46:29.172967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '646063b9a8a7'
down_revision = 'fe566d6c618a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True, comment='大小'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=100),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=100),
               comment='',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('desc',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('size')

    # ### end Alembic commands ###
