FROM dp-harbor.zhito.com/vehicle/integration-server:20230915

# 安装 Git
RUN apt-get update && apt-get install -y git

WORKDIR /app

COPY app /app/server

WORKDIR /app/server

# 设置环境变量
CMD ["export FLASK_ENV=development"]

# 安装 Python 依赖
RUN python3.10 -m pip install -r requirements.txt --index https://pypi.tuna.tsinghua.edu.cn/simple

# # 执行 Flask 数据库迁移
RUN python3.10 -m flask db upgrade

EXPOSE 9021

# 启动 Gunicorn 服务器
CMD ["./start.sh"]
